#define MYPORT "19543"
#define MYIP "127.0.0.1"
#define BACKLOG 10
#define NAMELENGTH 32
#define BUFFERSIZE 256
#define MAXUSERS 5
#define USERNAME_MIN 3
#define USERNAME_MAX 32
#define PASSWORD_MIN 4
#define PASSWORD_MAX 8
#define USERS_FILE "data/users.txt"